export const userModelErrorCodes = Object.freeze({
    EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
    CREATE_USER_FAILED: "CREATE_USER_FAILED",
    LOGIN_FAILED: "LOGIN_FAILED",
    VERIFY_EMAIL_FAILED: "VERIFY_EMAIL_FAILED",
    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID_TOKEN: "INVALID_TOKEN",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    SERVER_ERROR: "SERVER_ERROR",
    INVALID_TEAM_CODE: "INVALID_TEAM_CODE",
    ACCOUNT_CREATION_ERROR: "ACCOUNT_CREATION_ERROR",
    USER_DIRECTORY_CREATION_ERROR: "USER_DIRECTORY_CREATION_ERROR",
    TEAM_ALREADY_FULL: "TEAM_ALREADY_FULL",
    EMAIL_VERIFICATION_CREATION_ERROR: "EMAIL_VERIFICATION_CREATION_ERROR",
    TEAM_NAME_ALREADY_TAKEN: "TEAM_NAME_ALREADY_TAKEN",
    TEAM_DIRECTORY_CREATION_ERROR: "TEAM_DIRECTORY_CREATION_ERROR",
});

export const userModelErrorMessage = Object.freeze({
    EMAIL_ALREADY_EXIST: "The email is already registered",
    EMAIL_NOT_VERIFIED: "The email is not verified",
    USER_NOT_FOUND: "The email is not registered, please register first",
    WRONG_PASSWORD: "The password is not match with the password stored",
    INVALID_VERIFICATION_CODE: "The verification code is either wrong, invalid, or null",
    CREATE_USER_FAILED: "There is an error while creating your data",
    LOGIN_FAILED: "There is an error while log in to your account",
    VERIFY_EMAIL_FAILED: "There is an error while verify your email",
    UNAUTHORIZED: "The token is not authorized, please register and verify",
    INVALID_TOKEN: "The token either wrong or invalid",
    SESSION_EXPIRED: "The log in session has expired",
    SERVER_ERROR: "The server returned an error",
    INVALID_TEAM_CODE: "The team code is either wrong or invalid",
    ACCOUNT_CREATION_ERROR: "An error occured when creating the account",
    USER_DIRECTORY_CREATION_ERROR: "An error occured when creating the user directory",
    TEAM_ALREADY_FULL: "The team is already full, please remove another member, create a new team, or join another team",
    EMAIL_VERIFICATION_CREATION_ERROR: "An error occured when creating email verification",
    TEAM_NAME_ALREADY_TAKEN: "The team name is already taken by another team, please use another name",
    TEAM_DIRECTORY_CREATION_ERROR: "An error occured when creating the team directory",
});